source 'https://rubygems.org'

gem 'cookbook-development', :git => 'https://github.com/RallySoftware-cookbooks/cookbook-development'
#gem 'cookbook-development', :path => '~/projects/cookbook-development'

gem 'kitchen-docker-api', '~> 0.1'
